"""Print metrics generated by ``evaluate.py``; this module never simulates results."""
import json
from pathlib import Path

import pandas as pd


def compute_project_table(metrics_path="outputs/metrics.json"):
    path = Path(metrics_path)
    if not path.exists():
        raise FileNotFoundError(
            "No metrics file found. Run `python evaluate.py --split test` before creating tables."
        )
    metrics = json.loads(path.read_text(encoding="utf-8"))
    row = {
        "model": metrics["model_name"],
        "split": metrics["split"],
        "samples": metrics["samples"],
        **metrics["summary"],
    }
    table = pd.DataFrame([row])
    print(table.to_string(index=False))
    return table


if __name__ == "__main__":
    compute_project_table()
